[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws_secret_access_key\s*=\s*["']?[A-Za-z0-9/+=]{40}["']?'''
tags = ["AWS", "key"]

[[rules]]
id = "generic-secret-key"
description = "Generic Secret"
regex = '''(?i)secret_key\s*=\s*["'].*["']'''
tags = ["key", "generic"]
